### ISSUE TITLE
PHP Notice:  Undefined variable: domain

### ISSUE THREAD

**Issue by rask** [Seravo/wp-palvelu-plugin#18]
The plugin text domain loading method `loadTextdomain` throws said PHP notices on all page loads when the plugin is active (essentially always when used as a mu-plugin).

```

  public static function loadTextdomain() {

    // Load translations first from the languages directory
    $locale = apply_filters( 'plugin_locale', get_locale(), $domain );
    load_textdomain( 
            $domain, 
            WP_LANG_DIR . '/my-plugin/' . self::$domain . '-' . $locale . '.mo' 
    );

    // And then from this plugin folder
    load_muplugin_textdomain( 'wpp', basename( dirname(__FILE__) ) . '/languages' );
  }
```

`$domain` is not defined anywhere. Should those two instances be `self::$domain` or is something missing? Plugin version is 1.3.1 and a fresh `vagrant up` on the `seravo/wordpress` stack.

**Comment by anttiviljami** [comment]
Looking at the code it should definitely be `self::$domain`. Wanna make a PR? :)
